package com.dao;

import com.po.SysRoleResource;

import java.util.List;

public interface SysRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_role_resource
     *
     * @mbggenerated Sun Dec 10 18:42:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_role_resource
     *
     * @mbggenerated Sun Dec 10 18:42:40 CST 2017
     */
    int insert(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_role_resource
     *
     * @mbggenerated Sun Dec 10 18:42:40 CST 2017
     */
    int insertSelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_role_resource
     *
     * @mbggenerated Sun Dec 10 18:42:40 CST 2017
     */
    SysRoleResource selectByPrimaryKey(Integer id);

    List<SysRoleResource> selectByAny(SysRoleResource sysRoleResource);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_role_resource
     *
     * @mbggenerated Sun Dec 10 18:42:40 CST 2017
     */
    int updateByPrimaryKeySelective(SysRoleResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_role_resource
     *
     * @mbggenerated Sun Dec 10 18:42:40 CST 2017
     */
    int updateByPrimaryKey(SysRoleResource record);
}